// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeYjySQKXTiGr_2KAdfYD6eteFdGwWYM',
    appId: '1:1003534704315:web:121e4975f7026cc889539e',
    messagingSenderId: '1003534704315',
    projectId: 'babydays-papashi',
    authDomain: 'babydays-papashi.firebaseapp.com',
    storageBucket: 'babydays-papashi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BIRonu7L79FOdsUThA_BW8Bjv2Zio3w',
    appId: '1:1003534704315:android:a15833a3e9a3fc3689539e',
    messagingSenderId: '1003534704315',
    projectId: 'babydays-papashi',
    storageBucket: 'babydays-papashi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxL5a8ijNfuosjPOUQ6XJfbl5SdXSv5s',
    appId: '1:1003534704315:ios:aafa7a295501765389539e',
    messagingSenderId: '1003534704315',
    projectId: 'babydays-papashi',
    storageBucket: 'babydays-papashi.firebasestorage.app',
    iosBundleId: 'com.example.babydays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxL5a8ijNfuosjPOUQ6XJfbl5SdXSv5s',
    appId: '1:1003534704315:ios:aafa7a295501765389539e',
    messagingSenderId: '1003534704315',
    projectId: 'babydays-papashi',
    storageBucket: 'babydays-papashi.firebasestorage.app',
    iosBundleId: 'com.example.babydays',
  );
}
